# Generated by Django 5.1 on 2024-08-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0002_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='About')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
                ('img', models.ImageField(blank=True, upload_to='images/about', verbose_name='Img')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='AboutAchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Achive')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
                ('img', models.ImageField(blank=True, upload_to='images/about', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'AboutAchive',
                'verbose_name_plural': 'AboutAchive',
            },
        ),
        migrations.CreateModel(
            name='AboutIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='About')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
                ('img', models.ImageField(blank=True, upload_to='images/about', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'InAbout',
                'verbose_name_plural': 'InAbout',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_disease', models.CharField(max_length=100)),
                ('type_of_doctor', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='DoctorSelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='DoctorSelf')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
                ('img', models.ImageField(blank=True, upload_to='images/doctorself', verbose_name='Img')),
                ('text', models.CharField(blank=True, default='', max_length=100, verbose_name='Text')),
                ('textinfo', models.CharField(blank=True, default='', max_length=200, verbose_name='Textinfo')),
            ],
            options={
                'verbose_name': 'DoctorSelf',
                'verbose_name_plural': 'DoctorSelf',
            },
        ),
        migrations.CreateModel(
            name='FootetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Havolalar Nomi')),
            ],
            options={
                'verbose_name': 'FootetLink',
                'verbose_name_plural': 'FootetLink',
            },
        ),
        migrations.CreateModel(
            name='FootetLinkTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('link', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='testexam.footetlink', verbose_name='havolalar')),
            ],
            options={
                'verbose_name': 'FootetLinkTop',
                'verbose_name_plural': 'FootetLinkTop',
            },
        ),
        migrations.CreateModel(
            name='Medecine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='DoctorSelf')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
                ('img', models.ImageField(blank=True, upload_to='images/doctorself', verbose_name='Img')),
                ('text', models.CharField(blank=True, default='', max_length=100, verbose_name='Text')),
                ('textinfo', models.CharField(blank=True, default='', max_length=200, verbose_name='Textinfo')),
            ],
            options={
                'verbose_name': 'DoctorSelf',
                'verbose_name_plural': 'DoctorSelf',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Menu Nomi')),
                ('order', models.CharField(blank=True, default='', max_length=100, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Menyu',
                'verbose_name_plural': 'Menyu',
            },
        ),
        migrations.CreateModel(
            name='OnePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images/service', verbose_name='Img')),
                ('topname', models.CharField(blank=True, default='', max_length=100, verbose_name='Top name')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Base name')),
                ('text', models.CharField(default='', max_length=200, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'OnePage',
                'verbose_name_plural': 'OnePage',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='images/partner', verbose_name='Icon')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Hamkor Nomi')),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PartnersTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('info', models.CharField(blank=True, max_length=200, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'PartnersTop',
                'verbose_name_plural': 'PartnersTop',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='images/service', verbose_name='Icon')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Service Nomi')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ServiceTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('info', models.CharField(blank=True, max_length=200, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'ServiceTop',
                'verbose_name_plural': 'ServiceTop',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Specialist')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Info')),
                ('img', models.ImageField(blank=True, upload_to='images/about', verbose_name='Img')),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialist',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='SubMenu Nomi')),
                ('order', models.CharField(blank=True, default='', max_length=100, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Sub_Menyu',
                'verbose_name_plural': 'Sub_Menyu',
            },
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Test'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='Correct',
            field=models.CharField(max_length=100, verbose_name='To‘g‘ri javob'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option1',
            field=models.CharField(max_length=100, verbose_name='Variant_1'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option2',
            field=models.CharField(max_length=100, verbose_name='Variant_2'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option3',
            field=models.CharField(max_length=100, verbose_name='Variant_3'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option4',
            field=models.CharField(max_length=100, verbose_name='Variant_4'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Question',
            field=models.CharField(max_length=100, verbose_name='Savol'),
        ),
        migrations.AlterModelTable(
            name='exam',
            table=None,
        ),
        migrations.AddField(
            model_name='about',
            name='achive',
            field=models.ManyToManyField(to='testexam.aboutachive', verbose_name='Achive'),
        ),
        migrations.AddField(
            model_name='about',
            name='inabout',
            field=models.ManyToManyField(to='testexam.aboutin', verbose_name='InAbout'),
        ),
        migrations.AddField(
            model_name='menu',
            name='submenu',
            field=models.ManyToManyField(blank=True, default='', max_length=500, to='testexam.submenu', verbose_name='Submenu'),
        ),
    ]
