# Generated by Django 5.1 on 2024-09-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0007_remove_useranswer_answer_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
