# Generated by Django 5.1 on 2024-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0009_alter_question_answer_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Contact')),
                ('info', models.CharField(blank=True, default='', max_length=200, verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.AlterField(
            model_name='medecine',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Medecine'),
        ),
    ]
