# Generated by Django 5.1 on 2024-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0010_contact_alter_medecine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorself',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/images/doctorself', verbose_name='Img'),
        ),
    ]
