# Generated by Django 5.1.1 on 2024-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0012_alter_about_img_alter_aboutachive_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'DiseaseType',
                'verbose_name_plural': 'DiseaseType',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'DoctorSpec',
                'verbose_name_plural': 'DoctorSpec',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/about', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='aboutachive',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/about', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='aboutin',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/about', verbose_name='Icon'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type_of_disease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type_of_doctor',
        ),
        migrations.AlterField(
            model_name='doctorself',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/doctorself', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='medecine',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/medicine', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='onepage',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/onepage', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/partner', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/service', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/specialist', verbose_name='Img'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_of_disease',
            field=models.ManyToManyField(to='testexam.diseasetype', verbose_name='Kasallik turi'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_of_doctor',
            field=models.ManyToManyField(to='testexam.doctorspec', verbose_name='Doktor mutaxassisligi'),
        ),
    ]
