# Generated by Django 5.1.1 on 2024-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0013_diseasetype_doctorspec_alter_about_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type_of_disease',
            field=models.ManyToManyField(related_name='disease', to='testexam.diseasetype', verbose_name='Kasallik turi'),
        ),
    ]
