# Generated by Django 5.1.1 on 2024-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0014_alter_appointment_type_of_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type_of_doctor',
            field=models.ManyToManyField(related_name='doctors', to='testexam.doctorspec', verbose_name='Doktor mutaxassisligi'),
        ),
    ]
