# Generated by Django 5.1 on 2024-11-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0017_remove_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type_of_disease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='type_of_doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_of_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease', to='testexam.diseasetype', verbose_name='Kasallik turi'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_of_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='testexam.doctorspec', verbose_name='Doktor mutaxassisligi'),
        ),
    ]
