# Generated by Django 5.1 on 2024-11-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0020_telegramuser_delete_telegrammessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
