# Generated by Django 5.1 on 2024-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0021_delete_telegramuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='admin_message',
            field=models.TextField(blank=True, null=True, verbose_name='Admin javobi'),
        ),
    ]
