# Generated by Django 5.1 on 2024-11-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testexam', '0023_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
